version: "3.8"

services:
  node:
    build:
      context: ./../Docker/Dockerfiles/Backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./../Node:/usr/src/app
    depends_on:
      - postgres

  vue:
    build:
      context: ./../Docker/Dockerfiles/Frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./../Vue:/usr/src/app
    depends_on:
      - node

  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
